name: ZiiMCrates
version: ${project.version}
main: me.ziim.crates.ZiiMCrates
api-version: 1.16
authors: [ ZiiM ]
description: A simple crates mod by ZiiM
website: https://github.com/ZiiMs/ZiiM-Crates

commands:
  cratetool:
    description: Creates a crate for RNG loot
    usage: §eUSAGE /cratetool <crate name>
    permission: zc.createcrate
  getkey:
    description: Gives you the key for specified crate
    usage: §eUSAGE /getkey <crate id>
    permission: zc.getkey
